FROM golang:1.11
WORKDIR /usr/src/app
COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -o collector.bin collector/collector.go

FROM alpine:latest
RUN apk update && apk add ca-certificates && rm -rf /var/cache/apk/*
COPY --from=0 /usr/src/app/collector.bin /go/bin/collector
ENTRYPOINT [ "/go/bin/collector" ]
